{
    "name": "POS Hotel INTC",
    "version": "19.0.1.0.11",
    "category": "Point of Sale",
    "summary": "Transfert des consommations POS vers les chambres d'hôtel",
    "depends": ["point_of_sale", "hotel"],
    "data": [
        "security/ir.model.access.csv",
        "data/night_audit_sequence.xml",
        "views/night_audit_views.xml",
        "views/report_invoice_inherit.xml",
        "views/pos_payment_method_views.xml",
        "wizards/folio_settle_wizard_views.xml",
        "wizards/order_cancel_wizard_views.xml",
        "wizards/add_room_wizard_views.xml",
        "wizards/remove_room_wizard_views.xml",
        "wizards/checkin_wizard_views.xml",
        "wizards/charge_cancel_wizard_views.xml",
        "wizards/charge_refund_wizard_views.xml",
        "wizards/charge_add_wizard_views.xml",
        "wizards/charge_add_service_wizard_views.xml",
        "views/sale_order_views.xml",
        "views/sale_order_action_views.xml",
        "views/sale_advance_payment_inv_views.xml",
    ],
    "assets": {
        "point_of_sale._assets_pos": [
            "POS_HOTEL_INTC/static/src/app/overrides/data_service_patch.js",
            "POS_HOTEL_INTC/static/src/scss/room_removed_line.scss",
            "POS_HOTEL_INTC/static/src/app/screens/payment_screen/payment_screen.js",
            "POS_HOTEL_INTC/static/src/app/screens/payment_screen/payment_screen.xml",
            "POS_HOTEL_INTC/static/src/app/screens/payment_screen/room_charge_popup/room_charge_popup.js",
            "POS_HOTEL_INTC/static/src/app/screens/payment_screen/room_charge_popup/room_charge_popup.xml",
        ],
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}