from . import pos_payment_method
from . import pos_session
from . import resource_resource
from . import res_partner
from . import folio_charge
from . import sale_order
from . import pos_order
from . import sale_order_line
from . import product_pricing
from . import utm_source
from . import rental_order_wizard
from . import room_removal_log
from . import planning_slot
from . import sale_advance_payment_inv
from . import night_audit
from . import account_move